<a href="https://colab.research.google.com/github/claudiaariyani/claudiaariyani_/blob/main/Missing_value_dengan_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

2. Baca dataset dengan memanfaatkan library pandas dan numppy sbb

In [11]:
#Libararies
import pandas as pd
import numpy as np

# baca file dataset
df = pd.read_csv("/content/apartemen2 (1).csv")

#Melihat semua isi data
(df)

   KodeApt   Wilayah St_Milik Jum_kamar
0    104.0    Bantul        Y         3
1    197.0    Sleman        N         3
2      NaN    Sleman        N       NaN
3    201.0     Yogya       12         1
4    203.0     Yogya        Y         3
5    207.0     Yogya        Y       NaN
6      NaN  KL-Progo      NaN         2
7    213.0    Bantul        Y        --
8    215.0    Bantul        Y        na

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

3. Cek adakah data null, jika ada berapa jumlahnya?

In [3]:
# cek ada missing value
df.isnull().values.any()

np.True_

In [4]:
# Banyaknya missing values?
df.isnull().sum().sum()

np.int64(5)

4. Melihat data pada kolom KodeApt dan mengecek data null ada kolom tersebut

In [5]:
# Melihat kolom KodeApt
df['KodeApt']

0    104.0
1    197.0
2      NaN
3    201.0
4    203.0
5    207.0
6      NaN
7    213.0
8    215.0
Name: KodeApt, dtype: float64

In [6]:
df['KodeApt'].isnull()

0    False
1    False
2     True
3    False
4    False
5    False
6     True
7    False
8    False
Name: KodeApt, dtype: bool

5. Melihat data pada kolom Jum_Kamar dan mengecek data null ada kolom

In [7]:
#Melihat kolom Jum_Kamar
df['Jum_kamar']

0      3
1      3
2    NaN
3      1
4      3
5    NaN
6      2
7     --
8     na
Name: Jum_kamar, dtype: object

In [8]:
df['Jum_kamar'].isnull()

0    False
1    False
2     True
3    False
4    False
5     True
6    False
7    False
8    False
Name: Jum_kamar, dtype: bool

6. Membuat daftar missing value dam cek kembali data pada kolom Jum_kamar (no 7 dan no 8). Apa artinya?

Artinya....

In [30]:
# Membuat daftar missing value
missing_values = ["n/a", "na", "--"]
df = pd.read_csv("/content/apartemen2 (1).csv", na_values = missing_values)

In [10]:
df['Jum_kamar']

0    3.0
1    3.0
2    NaN
3    1.0
4    3.0
5    NaN
6    2.0
7    NaN
8    NaN
Name: Jum_kamar, dtype: float64

In [31]:
df['Jum_kamar'].isnull()

0    False
1    False
2     True
3    False
4    False
5     True
6    False
7     True
8     True
Name: Jum_kamar, dtype: bool

7. Membuat daftar missing value dan cek data pada kolom St_Milik(no3)



Artinya....

In [32]:
df['St_Milik']

0      Y
1      N
2      N
3     12
4      Y
5      Y
6    NaN
7      Y
8      Y
Name: St_Milik, dtype: object

In [33]:
df['St_Milik'].isnull()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
7    False
8    False
Name: St_Milik, dtype: bool

8. Medeteksi angka(sebagai missing value) pada kolom yang bertipe non numerik dan cekdata pada kolom St_Milik(no 3). Apa artinya?


Artinya....

In [34]:
# Deteksi angka
cnt = 0

for row in df['St_Milik']:
    try:
        int(row)
        df.loc[cnt, 'St_Milik'] = np.nan
    except (ValueError, TypeError):
        pass

    cnt += 1

df['St_Milik'].isnull()

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7    False
8    False
Name: St_Milik, dtype: bool

9. Hitung kembali total missing value pada setiap kolom

In [35]:
# Total missing value pada setiap kolom
df.isnull().sum()

KodeApt      2
Wilayah      0
St_Milik     2
Jum_kamar    4
dtype: int64

In [36]:
# Banyaknya missing values
df.isnull().sum().sum()

np.int64(8)

10. Mengisi missing value dengan angka pada lokasi yang spesifik

In [38]:
# Mengganti missing values dengan sebuah angka
df['KodeApt'].fillna(837, inplace=True)
print(df.KodeApt)

0    104.0
1    197.0
2    837.0
3    201.0
4    203.0
5    207.0
6    837.0
7    213.0
8    215.0
Name: KodeApt, dtype: float64

In [39]:
#Mengganti pada lokasi spesifik
df.loc[2, 'KodeApt'] = 8837
print(df.KodeApt)

0     104.0
1     197.0
2    8837.0
3     201.0
4     203.0
5     207.0
6     837.0
7     213.0
8     215.0
Name: KodeApt, dtype: float64

11. Mengisi missing value dengan nilai median

In [41]:
#Mengganti missing value dengan median
median = df['Jum_kamar']. median()
df['Jum_kamar'].fillna(median, inplace=True)
print(df.Jum_kamar)

0    3.0
1    3.0
2    3.0
3    1.0
4    3.0
5    3.0
6    2.0
7    3.0
8    3.0
Name: Jum_kamar, dtype: float64

/tmp/ipykernel_1508/1728240885.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Jum_kamar'].fillna(median, inplace=True)

12. Melihat keseluruhan data

In [43]:
(df)

   KodeApt   Wilayah St_Milik  Jum_kamar
0    104.0    Bantul        Y        3.0
1    197.0    Sleman        N        3.0
2   8837.0    Sleman        N        3.0
3    201.0     Yogya      NaN        1.0
4    203.0     Yogya        Y        3.0
5    207.0     Yogya        Y        3.0
6    837.0  KL-Progo      NaN        2.0
7    213.0    Bantul        Y        3.0
8    215.0    Bantul        Y        3.0

13. Mengganti data non numerik pada lokasi yang spesifik

In [45]:
# Mengganti pada lokasi spesifik pada kolom St_milik
df.loc[3, 'St_Milik'] = 'N'
df.loc[6, 'St_Milik'] = 'Y'
(df.St_Milik)

0    Y
1    N
2    N
3    N
4    Y
5    Y
6    Y
7    Y
8    Y
Name: St_Milik, dtype: object

In [46]:
(df)

   KodeApt   Wilayah St_Milik  Jum_kamar
0    104.0    Bantul        Y        3.0
1    197.0    Sleman        N        3.0
2   8837.0    Sleman        N        3.0
3    201.0     Yogya        N        1.0
4    203.0     Yogya        Y        3.0
5    207.0     Yogya        Y        3.0
6    837.0  KL-Progo        Y        2.0
7    213.0    Bantul        Y        3.0
8    215.0    Bantul        Y        3.0

14. Simpan model

In [47]:
# Simpan data
df.to_csv('Apartemen_ok.csv')

#df.to_csv('Apartemen_ok.csv', header= False )
#df.to_csv(r'C:\Users\Admin\Desktop\Apartemen_ok.csv', index=False

15. Mengubah data non numerik menjadi numerik

In [49]:
# Libraries
from sklearn.preprocessing import LabelEncoder
from pandas import DataFrame
import pandas as pd
import numpy as np

# Melihat semua isi data
print(df)
le = LabelEncoder()

for col in df.columns.values:
    # Encoding pada variable kategoriyal16
    if df[col].dtypes == 'object':
        # Menggunakan pd.concat sebagai pengganti .append yang sudah deprecated/dihapus
        data = pd.concat([df[col], df[col]])
        le.fit(data.values)
        df[col] = le.transform(df[col])

df.head(10)

   KodeApt   Wilayah St_Milik  Jum_kamar
0    104.0    Bantul        Y        3.0
1    197.0    Sleman        N        3.0
2   8837.0    Sleman        N        3.0
3    201.0     Yogya        N        1.0
4    203.0     Yogya        Y        3.0
5    207.0     Yogya        Y        3.0
6    837.0  KL-Progo        Y        2.0
7    213.0    Bantul        Y        3.0
8    215.0    Bantul        Y        3.0

   KodeApt  Wilayah  St_Milik  Jum_kamar
0    104.0        0         1        3.0
1    197.0        2         0        3.0
2   8837.0        2         0        3.0
3    201.0        3         0        1.0
4    203.0        3         1        3.0
5    207.0        3         1        3.0
6    837.0        1         1        2.0
7    213.0        0         1        3.0
8    215.0        0         1        3.0

16. Simpan data

In [51]:
df.to_csv('Apartemen_numerik.csv', header = True, index=False)